# mysql datasource info
#riot.datasource:
#    dataSourceName: 'riotdbappid'
#    driverClassName: 'com.mysql.cj.jdbc.Driver'
#    username: 'Styrfire'
#    password: 'bga6+pEEHd#EY3?S'
#    url: 'jdbc:mysql://riotstaticdatadb.cdfpu262rtej.us-east-1.rds.amazonaws.com:3306'

# sqlite datasource info
riot.datasource:
    dataSourceName: 'riotdbappid'
    driverClassName: 'org.sqlite.JDBC'
    username: ''
    password: ''
    url: 'riotstaticdatadb.db'
#    url: 'jdbc:sqlite::resource:sqlite/riotstaticdatadb.db'

#400 = draft pick
#420 = ranked solo
queue: 420

# comment out or set to -1 to grab data from beginning of season
timestamp.numOfWeeks: 1

logging.level.root: INFO #DEBUG