# sqlite datasource info
riot.datasource:
    dataSourceName: 'riotdbappid'
    driverClassName: 'org.sqlite.JDBC'
    username: ''
    password: ''
    url: 'jdbc:sqlite:C:/Users/g_n_r/Desktop/Riot SQLite Database/sqlite/riotstaticdatadb.db'

#400 = draft pick
#420 = ranked solo
queue: 420

# comment out or set to -1 to grab data from beginning of season
timestamp.numOfWeeks: 1

logging.level.root: INFO #DEBUG